/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    screens: {
      monitor: "1800px",
      desktop: "1200px",
      tablet: "900px",
      mobile: "600px",
      "small-mobile": "400px",
      "max-monitor": { max: "1800px" },
      "max-desktop": { max: "1200px" },
      "max-tablet": { max: "900px" },
      "max-mobile": { max: "600px" },
      "max-small-mobile": { max: "400px" },
    },
    colors: {
      transparent: "transparent",
      inherit: "inherit",
      white: "#FFFFFF",
      offWhite: "#f1f1f1",
      black: "#000000",
      dark: "#1E2022",
      dim: "#0000004D",
      "cool-white": "#CFD0D3",
      "subtle-white": "#EFF2F2",
      gray: "#77838F",
      "light-gray": "#9EA1B4",
      "search-gray": "#F3F8F7",
      green: "rgba(0, 170, 78, 1)",
      "dark-green": "#008370",
      "light-green": "#F1FAF9",
      "gray-500": "#5C6574",
      "gray-background": "#EFF2F2",
      "black-shade": "#0F111D",
      red: "#E01B22",
      card: "#EFF3F2",
      blue: "rgba(22, 36, 89, 1)",
      "gray-13": "rgba(111, 111, 111, 0.2)",
      mainTitle: "#E3E6F7",
      success: "#00AA4E",
      primary: "#162459",
      yellow: "#FEDC00",
      tableContainer: "#F3F6F8",
      headerBg: "#E3E6F7",
      themeColor: "#162459",
      grey: "#7C876E",
      "gray-1": "#4B4B4B",
      "light-gray": "#e3e7f7",
    },
    boxShadow: {
      none: "none",
      lg: "0px 2px 48px rgba(0, 0, 0, 0.06)",
      card: "0px 2px 4px rgba(220, 219, 222, 0.31)",
      search: "0px 4px 4px rgba(130, 134, 157, 0.08)",
      "check-icon": "0px 7.5px 20px rgba(0, 0, 0, 0.16)",
      "partner-card": "0px 0px 0px 1px rgba(51, 68, 99, 0.06);",
    },
    borderRadius: {
      none: "0px",
      xs: "2px",
      sm: "4px",
      md: "8px",
      lg: "12px",
      xl: "16px",
      "2xl": "18px",
      "pop-up": "25px",
      "3xl": "32px",
      search: "60px",
      full: "999px",
    },
    fontSize: {
      xs: ["10px", { lineHeight: "10px" }],
      sm: ["12px", { lineHeight: "14px" }],

      md: ["14px", { lineHeight: "21px" }],
      lg: ["16px", { lineHeight: "22px" }],
      xl: ["18px", { lineHeight: "24px" }],
      "2xl": ["20px", { lineHeight: "28px" }],
      "2xl-line-height": ["22px", { lineHeight: "32px" }],
      "3xl": ["25px", { lineHeight: "36px" }],
      "4xl": ["32px", { lineHeight: "48px" }],
      "5xl": ["36px", { lineHeight: "54px" }],
      "6xl": ["40px", { lineHeight: "60px" }],
      "7xl": ["68px", { lineHeight: "72px" }],
    },
    fontFamily: {
      poppins: "Poppins, sans-serif",
      "dm-sans": "DMSans, sans-serif",
    },
    extend: {
      backgroundSize: {
        auto: "auto",
        cover: "cover",
        contain: "contain",
        size50: "50%",
      },
      backgroundImage: {
        "main-linear-gradient":
          "radial-gradient(circle, rgb(199 207 239) 0%, rgba(255,255,255,1) 100%)",
      },
      animation: {
        loader: "loader 0.6s infinite alternate",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        loader: {
          to: {
            opacity: 0.65,
            transform: "translate3d(0, -1rem, 0)",
          },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
